#!/bin/bash
# @file
# Simple script to run the given command for all enabled runners.

set -e $DRUPAL_TI_DEBUG

CMD=$1

if [ -z "$CMD" -o -z "$DRUPAL_TI_RUNNERS" ]
then
	echo "Usage: $0 <cmd>" 1>&2
	echo "" 1>&2
	echo "- cmd: A valid travis-ci command, e.g. before-script, script, after-script." 1>&2
	exit 1
fi

### Path resolving from drush/drush:drush

# Get the absolute path of this executable
SELF_DIRNAME=$(dirname -- $0)
SELF_PATH=$(cd -P -- "$SELF_DIRNAME" && pwd -P)/$(basename -- $0)

# Resolve symlinks - this is the equivalent of "readlink -f", but also works with non-standard OS X readlink.
while [ -h "$SELF_PATH" ]; do
    # 1) cd to directory of the symlink
    # 2) cd to the directory of where the symlink points
    # 3) Get the pwd
    # 4) Append the basename
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink "$SELF_PATH")
    SYM_DIRNAME=$(dirname -- "$SYM")
    SELF_PATH=$(cd "$DIR" && cd "$SYM_DIRNAME" && pwd -P)/$(basename -- "$SYM")
done

# Build the path to our script dir.
SCRIPT_DIR=$(dirname "$SELF_PATH")

for RUNNER in $DRUPAL_TI_RUNNERS
do
	SCRIPT="$SCRIPT_DIR/runners/$RUNNER/$CMD.sh"
	if [ -x "$SCRIPT" ]
	then
		"$SCRIPT"
	fi
done

# Ensure we don't exit with error status code.
exit 0
